title: Tabletop Exercise
author:
  name: Douglas BergÃ¨re
  email: douglas@uta.edu
description: >- # this means to ignore newlines until "baseurl:"
  February 2026 OIT Business Continuity and Information Security Tabletop Exercise
baseurl: "/tabletop" # the subpath of your site, e.g. /blog
timezone: America/Chicago
url: "https://uta-douglas.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: douglas_uta
github_username:  uta-douglas
