site_name: Business Continuity Tabletop Exercise
nav: 
 - Participant Home: index.md
<!-- - Injection #1 : injection1.md
<!-- - Injection #2 : injection2.md
<!-- - Injection #3 : injection3.md -->

stylesheets:
extra.css:
.nav-link[rel="next"] {display: none;}
.nav-link[rel="prev"] {display: none;}
