site_name: Business Continuity Tabletop Exercise
nav: 
 - Participant Home: index.md
 - 1 : injection1

stylesheets:
extra.css:
.nav-link[rel="next"] {display: none;}
.nav-link[rel="prev"] {display: none;}
